# Generated by Django 3.1.1 on 2020-09-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20200904_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('-created_date',), 'verbose_name': 'pet', 'verbose_name_plural': 'pets'},
        ),
    ]
