# Generated by Django 3.1.1 on 2020-09-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200904_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-created_date',), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
