# Generated by Django 3.1.1 on 2020-09-03 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True, verbose_name="Data")),
                ("reason", models.CharField(max_length=200, verbose_name="Motivo")),
                ("current_weight", models.FloatField(verbose_name="Peso Atual")),
                (
                    "current_drugs",
                    models.TextField(blank=True, verbose_name="Medicamento Atual"),
                ),
                (
                    "prescribed_drugs",
                    models.TextField(verbose_name="Medicamentos Prescritos"),
                ),
                (
                    "prescribed_exams",
                    models.TextField(verbose_name="Exames Prescritos"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pets.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "consulta",
                "verbose_name_plural": "consultas",
            },
        ),
    ]
