# Generated by Django 3.1.1 on 2020-09-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Data da Consulta"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.CharField(max_length=200, verbose_name="Motivo da Consulta"),
        ),
    ]
