# Generated by Django 3.1.1 on 2020-09-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_auto_20200902_2350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="prescribed_exams",
            field=models.TextField(blank=True, verbose_name="Exames Prescritos"),
        ),
    ]
