# Generated by Django 3.1.1 on 2020-09-04 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20200903_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
