# Generated by Django 3.1.1 on 2020-09-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20200904_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-created_date',), 'verbose_name': 'consulta', 'verbose_name_plural': 'consultas'},
        ),
    ]
